### ISSUE TITLE
unbound: Allow easier DNS-over-TLS configuration

### ISSUE THREAD

**Issue by jpawlowski** [opnsense/plugins#1778]
Currently "Enable Forwarding Mode" will not consider that upstream servers might be DNS-over-TLS or DNS-over-HTTPS aware.

The "General configuration" shall provide an option to mark a server for those protocols and use the respective ports if no explicit port was set. Unbound shall then make use of that information to properly configure the forward section. This will avoid to use "Custom options" for it.

Please also consider to add "tls-cert-bundle: /etc/ssl/cert.pem" to the "server:" section to ensure that the upstream servers can be validated properly.

This is what I must currently put manually to the "Custom options":

```````
server:
  minimal-responses: yes
  qname-minimisation: yes
  rrset-roundrobin: yes
  use-caps-for-id: yes
  tls-cert-bundle: /etc/ssl/cert.pem

forward-zone:
  name: "."
  forward-addr: 2606:4700:4700::1111@853
  forward-addr: 1.1.1.1@853
  forward-addr: 2606:4700:4700::1001@853
  forward-addr: 1.0.0.1@853
  forward-ssl-upstream: yes
```````
