### ISSUE TITLE
[os-telegraf] Support [[inputs.suricata]]

### ISSUE THREAD

**Issue by psychogun** [opnsense/plugins#2475]
Edit: 
* OPNsense 21.1.8_1-amd64
* InfluxDB 2.0.7
* Telegraf 1.19.0

I am unable to get Intrusion Dectection Alerts to populate data to InfluxDBv2. Enabling "Intrusion Detection Alerts" in Telegraf > Input section, do create a section in the `telegraf.conf` file;
```bash
[[inputs.tail]]
  data_format = "json"
  files = ["/var/log/suricata/eve.json"]
  name_override = "suricata"
  tag_keys = ["event_type","src_ip","src_port","dest_ip","dest_port"]
  json_string_fields = ["*"]
```
but nothing ever gets into InfluxDBv2. The file `eve.json` do contain JSON data. 

I am unable to get `debug` log of my Telegraf installation, I do not know if this is related to why not `[[inputs.tail]]` is not working. All other data from the Telegraf plugin in OPNsense is showing just fine in InfluxDBv2 and I am able to create Dashboards in InfluxDBv2 with those data, however nothing related to IPS/IDS. 

(This error message might not be related):
```bash
2021-07-24T20:38:19 |   | I! Starting Telegraf 1.19.0 |  
-- | -- | -- | --
  |   | time="2021-07-24T22:38:19+02:00" level=error msg="failed to open. Ignored. open /.cache/snowflake/ocsp_response_cache.json: no such file or directory\n" func="gosnowflake.(*defaultLogger).Errorf" file="log.go:120" |  
  |   | time="2021-07-24T22:38:19+02:00" level=error msg="failed to create cache directory. /.cache/snowflake, err: mkdir /.cache: permission denied. ignored\n" func="gosnowflake.(*defaultLogger).Errorf" file="log.go:120"
```

Anyways, I would like to use instead, I think, the already created plugin for Suricata: https://github.com/influxdata/telegraf/tree/master/plugins/inputs/suricata

To be able to do this, checking a corresponding box in Telegraf would have to do two / three things (as stated in the documentation linked above); 

- Intrusion Detection would (also) have to generate output to unix_stream (the file which clearly states custom configuration should go here, `/usr/local/etc/suricata/custom.yaml`, is overwritten when the firewall is rebooted, btw);
```
- eve-log:
    enabled: yes
    filetype: unix_stream
    filename: /tmp/suricata-stats.sock
    types:
      - stats:
         threads: yes
```
PS: There seems to be a bit discrepancy regarding if it should be `filetype: unix_stream` or `type: unix_stream`(in the forum post down below).

- And to enable `[[inputs.suricata]]` in Telegraf, this has to be added to `telegraf.conf`:
```
[[inputs.suricata]]
  ## Data sink for Suricata stats log.
  # This is expected to be a filename of a
  # unix socket to be created for listening.
  source = "/var/run/suricata-stats.sock"

  # Delimiter for flattening field keys, e.g. subitem "alert" of "detect"
  # becomes "detect_alert" when delimiter is "_".
  delimiter = "_"
```

- And if that was not enough; 

> FreeBSD tuning

> Under FreeBSD it is necessary to increase the localhost buffer space to at least 16384, default is 8192 otherwise messages from Suricata are truncated as they exceed the default available buffer space, consequently no statistics are processed by the plugin.

> `sysctl -w net.local.stream.recvspace=16384`
> `sysctl -w net.local.stream.sendspace=16384`

...

It might be easier to just get the "default" `[[inputs.tail]]` to function properly ?? :-) HOW / TEH WHY is it not working for me.

I would like to present IDS/IPS data in my InfluxDBv2 dashboard, either by getting `[[inputs.tail]]` to work or this one, `[[inputs.suricata]]`.

I have not found any documentation on how this would look like in a InfluxDBv2 dashboard - the IDS data from OPNsense through Telegraf. . Alternatives would be using Grafana or the Elastic Stack to present IDS/IPS data, as I have found guides for them. 

I have tried to do this manually by following this forum post; https://forum.opnsense.org/index.php?topic=16966.0 - adding tunables, service start|stop etc., but I am at a loss.

**Comment by psychogun** [comment]
Users having the same error message as me; https://github.com/influxdata/telegraf/issues/9407 - Some users inform that telegraf is starting, and yes it is starting here as well (as I can see all other inputs other than `[[inputs.tail]]`, but could there be more going on here. .  .

**Comment by psychogun** [comment]
This issue might be closed? If someone can fix permission issues I have on https://github.com/opnsense/plugins/issues/2239 ;)

**Comment by psychogun** [comment]
Well. No, that did not take. This is a hit that shows up in the "Alerts" tab in Intrusion Detection after I did the above. It has not generated anything in InfluxDBv2 - but in my mind it should have produced * something * in InfluxDBv2.


Timestamp | SID | Action | Interface | Source | Port | Destination | Port | Alert 
-- | -- | -- | -- | -- | -- | -- | -- | -- 
2021-07-29T21:56:21.330569+0200 | 2402000 | blocked |   | 123.123.123.123 | 46309 | 192.168.12.35 | 80 | ET DROP Dshield Block Listed Source group 1 |  

I'll be so blunt and I'll tag @rogercoll

**Comment by psychogun** [comment]
Looks like 
```
sysctl -w net.local.stream.recvspace=16384
sysctl -w net.local.stream.sendspace=16384
``` 
is not enough.

I have captured the output from `sudo -u telegraf nc -U -l /tmp/suricata-stats.sock` and searching for "timestamp" throughout the output, it looks as messages from Suricata are truncated.

The start of the output:
`{"timestamp":"2021-07-29T16:26:14.841116+0200","event_type":"stat (…)`

and throughout the output I have
`,"invalid{"timestamp":"2021-0` (…)
`0,"pseud{"timestam` (…)
`mcap_drop":0,"ps{"timestamp` (…)
`emcap_drop"{"timestamp":"2021-07-2`

If `{"timestamp":` is indeed a new eve-log entry, I would like to think I have to further increase the localhost buffer space, because it does not look like suricata has enough space to send the whole event for telegraf to process. Let us try with 24576 (3 times the default 8192).

There are no errors in telegraf (/var/log/telegraf.log) depicting this.

Getting suricata to write to a file, with `type : unix_stream` - I see that a whole event is in the range of ~22490 bytes long. 

En event should end with `}}}}}` (`(...) ":{"memuse":7164960}}}}}
{"timestamp":"2021`)

Hopefully 
```sysctl -a | grep local.stream
net.local.stream.recvspace: 24576
net.local.stream.sendspace: 24576
``` 
will suffice.

I'll wait for [[inputs.suricata]] to pick up some alert events. Hopefully this is useful information for whomever will eventually implement this feature request :)

**Comment by psychogun** [comment]
Another caveat regarding this [[inputs.suricata]] plugin is that the buffer space probably will be different for all the different firewalls out there. As I found out, on another firewall, was that setting the buffer space to `24576` was not enough. 

On this particular firewall I have 10+ interfaces. After some troubleshooting, I found out that the event sent from suricata on this firewall is much larger (probably due to the incrase of interfaces (??)), so I had to increase the buffer space to `131072` for Telegraf to parse the event correctly on this firewall.

And if that was not enough, as of today's date, the [[inputs.suricata]] plugin in Telegraf shipped with OPNsense is not able to parse "alerts" anyways. I found out this, because [[inputs.suricata]] was newly updated with the ability to do this, detect alerts; https://github.com/influxdata/telegraf/tree/master/plugins/inputs/suricata

When Telegraf in OPNsense is updated with the ability to parse alerts, it might be a viable option to use [[inputs.suricata]] instead of the default [[inputs.tail]] section - because how that one is configured, as linked above in a comment a couple of posts above, `telegraf` does not even have permissions to read the `var/log/suricata/eve.json` file. 

```  
  - eve-log:
      enabled: yes
      filetype: unix_stream
      filename: /tmp/suricata-stats.sock
      types:
        - stats:
           threads: yes
        - alert:
             # packet: yes              # enable dumping of packet (without stream segments)
             # metadata: no             # enable inclusion of app layer metadata with alert. Default yes
             # http-body: yes           # Requires metadata; enable dumping of http body in Base64
             # http-body-printable: yes # Requires metadata; enable dumping of http body in printable format

             # Enable the logging of tagged packets for rules using the
             # "tag" keyword.
             tagged-packets: yes

             http: yes
             tls: yes
```
