### ISSUE TITLE
net-mgmt/Telegraf: Support output WITH username/password to Elasticsearch

### ISSUE THREAD

**Issue by psychogun** [opnsense/plugins#2592]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

[x] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md

[x] I have searched the existing issues and I'm convinced that mine is new.

[x] The title contains the plugin to which this issue belongs

**Describe the bug**
I have a username and password protected Elasticsearch instance and the Telegraf plugin timeouts when trying to connect.
```
E! [telegraf] Error running agent: connecting output outputs.elasticsearch: Error connecting to output "outputs.elasticsearch": health check timeout: no Elasticsearch node available

E! [agent] Failed to connect to [outputs.elasticsearch], retrying in 15s, error was 'health check timeout: no Elasticsearch node available'
```

**To Reproduce**
1. Go to 'Services'
2. Click on 'Telegraf, Outpus'
3. Scroll down to 'Elasticsearch'
4. There is no option to input username, password, or select the protocol or use an api key.

**Expected behavior**
I would like to have the option to adjust these parameters:
- *ARRAY* of hosts
- protocol (http/https)
- api_key
- username
- password

and/or the log file should show the missing authentication credential error instead of "timeout" (?).

**Relevant log files**
The Elasticsearch instance is reachable from the firewall:
```
[user@opnsense ~]$ curl -XGET http://192.168.99.1:9200
{"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":"Basic realm=\"security\" charset=\"UTF-8\""}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/]","header":{"WWW-Authenticate":"Basic re[use[user@[user@[u[u[use[usery@[user[use[usery@[user[juse[u[u[u[u[user@opnsense ~]$ 
```

Sending with username and password:
```
[user@opnsense ~]$ curl -u elasticuser -XGET http://192.168.99.1:9200
Enter host password for user 'elasticuser':
{
  "name" : "elk",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "U5qFxzVvR4GEtXgcYxqN9A",
  "version" : {
    "number" : "7.15.1",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "83c34f456ae19d60e94d846e455e6a4409bba9ed",
    "build_date" : "2021-10-07T21:56:19.031608185Z",
    "build_snapshot" : false,
    "lucene_version" : "8.9.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
[user@opnsense ~]$ 
```

**Additional context**

This is an excerpt (from filebeat.yml) which shows different settings for the Elasticsearch **output**:
```
# ---------------------------- Elasticsearch Output ----------------------------
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["192.168.99.1:9200"]

  # Protocol - either `http` (default) or `https`.
  protocol: "http"

  # Authentication credentials - either API key or username/password.
  #api_key: "id:api_key"
  username: "elasticuser"
  password: "password"
```

**Environment**
- OPNsense 21.7.3_3-amd64
- FreeBSD 12.1-RELEASE-p20-HBSD
- OpenSSL 1.1.1l 24 Aug 2021
- os-telegraf 1.12.1
