### ISSUE TITLE
CSS Textarea for plugin/haproxy mapfile editing

### ISSUE THREAD

**Issue by TomFreudenberg** [opnsense/plugins#3198]
When editing large mapfile for haproxy configuration it is difficult to get errors while on line-breaks.

If the textarea for `mapfile.content` had not `word-wrap` enabled this would be great.

**Solution**

Add CSS:

```css
      textarea#mapfile\.content {
        white-space: pre;
      }
```

Is it possible to add this to the plugin?

![image](https://user-images.githubusercontent.com/410087/203306849-35853560-4467-4ec2-b69f-0a34a506941b.png)
