### ISSUE TITLE
mdns-repeater - Lack of MDNS relay for ipv6

### ISSUE THREAD

**Issue by deasmi** [opnsense/plugins#3352]
**Important notices**
Before you add a new report, we ask you kindly to acknowledge the following:

- [X] I have read the contributing guide lines at https://github.com/opnsense/plugins/blob/master/CONTRIBUTING.md
- [X] I have searched the existing issues, open and closed, and I'm convinced that mine is new.
- [X] When the request is meant for an existing plugin, I've added its name to the title.

**Is your feature request related to a problem? Please describe.**

mdns-repeater does not support ipv6, and the author seemingly has no intention of adding support.
https://github.com/geekman/mdns-repeater/issues/3

I now have an IPv6 only client subnet, and these become more common over time, using tayga to provide 6to4.

Printers, speakers and other devices are on a seperate subnet, do avertise their ipv6 addresses in MDNS, but as mdns-repeater doesn't support ipv6 doesn't repeat these into the ipv6 only subnet.

**Describe the solution you like**

Support for mdns relaying between suubnets using ipv6

**Describe alternatives you considered**

I have not come up with any workable workarounds but I can see the following options
* Write a patch for mdns-repeater
* Switch plugin to Avahi
* Add Avahi plug to provide choice

**Additional context**

https://forum.opnsense.org/index.php?topic=13238.0

EDIT: Spelling

**Comment by gijs007** [comment]
Can this issue be re-opened? It's still a valid problem.
I'm actually running into the same issue with Matter devices, which use IPv6 Link-Local addresses.

**Comment by BPplays** [comment]
just for everyone here to know avahi is packaged it's just not a plugin so it has to be configured manually

here is some basic ansible that should work, though you have to set firewall rules to allow traffic though manually in opnsense
```yaml
  tasks:
  - name: Install avahi
    community.general.pkgng:
      name: "avahi-app"
      state: present

  - name: Copy avahi-daemon.conf to server
    copy:
      src: "{{ playbook_dir }}/config/avahi/avahi-daemon.conf"
      dest: "{{ main_etc }}/avahi/avahi-daemon.conf"
    notify: Restart avahi-daemon


  - name: Enable dbus
    become: true
    ansible.builtin.service:
      name: dbus
      enabled: yes
      state: started

  - name: Enable avahi-daemon
    become: true
    ansible.builtin.service:
      name: avahi-daemon
      enabled: yes
      state: started


  handlers:
    - name: Restart avahi-daemon
      ansible.builtin.service:
        name: avahi-daemon
        state: restarted

```

here is my avahi config:
```ini
[server]
use-ipv4=yes
use-ipv6=yes
check-response-ttl=no
use-iff-running=no

[publish]
publish-addresses=yes
publish-hinfo=yes
publish-workstation=no
publish-domain=yes

[reflector]
enable-reflector=yes
reflect-ipv=no

[rlimits]
rlimit-core=0
rlimit-data=4194304
rlimit-fsize=0
rlimit-nofile=30
rlimit-stack=4194304
rlimit-nproc=3
```
